import { StyleSheet } from 'react-native';
import { COLORS } from '../../../../constants/colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.white,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.lightGray,
    },
    backButton: {
        padding: 4,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: COLORS.text,
    },
    scrollContent: {
        padding: 24,
    },
    warningCard: {
        backgroundColor: '#FFF5F5',
        padding: 24,
        borderRadius: 20,
        alignItems: 'center',
        marginBottom: 32,
        borderWidth: 1,
        borderColor: '#FFE5E5',
    },
    warningTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FF3B30',
        marginTop: 16,
        marginBottom: 8,
    },
    warningText: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        lineHeight: 22,
    },
    consequences: {
        marginBottom: 40,
        paddingHorizontal: 10,
    },
    consequenceItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    bullet: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: COLORS.gray,
        marginRight: 12,
    },
    consequenceText: {
        fontSize: 14,
        color: COLORS.text,
        fontWeight: '500',
    },
    form: {
        width: '100%',
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.text,
        marginBottom: 12,
        textAlign: 'center',
    },
    input: {
        backgroundColor: '#F8FAFC',
        borderRadius: 12,
        paddingHorizontal: 16,
        height: 56,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        textAlign: 'center',
        fontSize: 18,
        fontWeight: 'bold',
        letterSpacing: 2,
        color: '#FF3B30',
        marginBottom: 24,
    },
    deleteButton: {
        backgroundColor: '#FF3B30',
        height: 56,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
        shadowColor: '#FF3B30',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    disabledButton: {
        backgroundColor: '#FFBABA',
        shadowOpacity: 0,
        elevation: 0,
    },
    deleteButtonText: {
        color: COLORS.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    cancelButton: {
        height: 56,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cancelButtonText: {
        color: COLORS.gray,
        fontSize: 16,
        fontWeight: '600',
    },
});
