import { StyleSheet, Dimensions, Platform } from 'react-native';
import { COLORS } from '../../../constants/colors';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scrollContent: {
        paddingBottom: 120,
    },
    heroContainer: {
        height: height * 0.45,
        width: '100%',
        position: 'relative',
    },
    heroImage: {
        width: '100%',
        height: '100%',
    },
    heroOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.3)',
    },
    headerNav: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 10,
    },
    navButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    restaurantBasicInfo: {
        position: 'absolute',
        bottom: 30,
        left: 20,
        right: 20,
    },
    cuisineBadge: {
        backgroundColor: COLORS.primary,
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 8,
        alignSelf: 'flex-start',
        marginBottom: 8,
    },
    cuisineText: {
        color: COLORS.white,
        fontSize: 12,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    restaurantName: {
        fontSize: 32,
        fontWeight: 'bold',
        color: COLORS.white,
        marginBottom: 8,
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: { width: -1, height: 1 },
        textShadowRadius: 10,
    },
    ratingLocationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
    },
    ratingBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    ratingText: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontSize: 14,
    },
    reviewsText: {
        color: 'rgba(255,255,255,0.8)',
        fontSize: 12,
    },
    locationBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        flex: 1,
    },
    locationText: {
        color: COLORS.white,
        fontSize: 14,
        fontWeight: '500',
    },
    reservationSection: {
        backgroundColor: COLORS.white,
        marginTop: -20,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        padding: 24,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 16,
        marginTop: 10,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: COLORS.text,
    },
    dateList: {
        paddingBottom: 10,
    },
    dateCard: {
        width: 60,
        height: 70,
        borderRadius: 16,
        backgroundColor: '#F8FAFC',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    activeDateCard: {
        backgroundColor: COLORS.primary,
        borderColor: COLORS.primary,
    },
    dateDay: {
        fontSize: 12,
        color: COLORS.gray,
        marginBottom: 4,
    },
    dateNum: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.text,
    },
    activeDateText: {
        color: COLORS.white,
    },
    timeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 10,
    },
    timeSlot: {
        width: (width - 68) / 4,
        paddingVertical: 10,
        borderRadius: 12,
        backgroundColor: '#F8FAFC',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    activeTimeSlot: {
        backgroundColor: COLORS.primary,
        borderColor: COLORS.primary,
    },
    timeText: {
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.text,
    },
    activeTimeText: {
        color: COLORS.white,
    },
    guestSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8FAFC',
        padding: 12,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    guestBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: COLORS.white,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    guestBtnText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: COLORS.primary,
    },
    guestCount: {
        fontSize: 20,
        fontWeight: 'bold',
        color: COLORS.text,
        marginHorizontal: 20,
    },
    guestLabel: {
        fontSize: 14,
        color: COLORS.gray,
        fontWeight: '500',
        marginLeft: 10,
    },
    infoSection: {
        padding: 24,
    },
    aboutTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.text,
        marginBottom: 10,
    },
    aboutText: {
        fontSize: 14,
        color: COLORS.gray,
        lineHeight: 22,
        marginBottom: 20,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 15,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderColor: COLORS.lightGray,
    },
    infoLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    infoLabel: {
        fontSize: 15,
        fontWeight: '500',
        color: COLORS.text,
    },
    preOrderSection: {
        padding: 24,
        backgroundColor: '#F0F7FF',
        marginHorizontal: 20,
        borderRadius: 20,
        marginBottom: 20,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    preOrderTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.text,
    },
    seeMenuText: {
        color: COLORS.primary,
        fontWeight: 'bold',
        fontSize: 14,
    },
    preOrderSubtitle: {
        fontSize: 14,
        color: COLORS.gray,
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: COLORS.white,
        paddingHorizontal: 20,
        paddingTop: 15,
        paddingBottom: Platform.OS === 'ios' ? 35 : 20,
        borderTopWidth: 1,
        borderTopColor: COLORS.lightGray,
    },
    mainActionButton: {
        backgroundColor: COLORS.primary,
        height: 64,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    btnContent: {
        flex: 1,
    },
    btnMainText: {
        color: COLORS.white,
        fontSize: 18,
        fontWeight: 'bold',
    },
    btnSubText: {
        color: 'rgba(255,255,255,0.8)',
        fontSize: 12,
    },
});
