import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../../constants/colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: COLORS.white,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.lightGray,
    },
    backButton: {
        padding: 4,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: COLORS.text,
    },
    scrollContent: {
        paddingBottom: 40,
    },
    searchSection: {
        backgroundColor: COLORS.white,
        padding: 24,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    welcomeText: {
        fontSize: 22,
        fontWeight: 'bold',
        color: COLORS.text,
        marginBottom: 16,
        textAlign: 'center',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F1F5F9',
        borderRadius: 12,
        paddingHorizontal: 16,
        height: 50,
    },
    searchInput: {
        flex: 1,
        marginLeft: 10,
        fontSize: 15,
        color: COLORS.text,
    },
    section: {
        marginTop: 32,
        paddingHorizontal: 20,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: COLORS.text,
        marginBottom: 16,
    },
    seeAllText: {
        fontSize: 14,
        color: COLORS.primary,
        fontWeight: '600',
    },
    contactCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.white,
        padding: 16,
        borderRadius: 20,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    contactIconWrapper: {
        width: 48,
        height: 48,
        borderRadius: 14,
        backgroundColor: '#F0F7FF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    contactTextContent: {
        flex: 1,
        marginLeft: 16,
    },
    contactTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: COLORS.text,
    },
    contactSubtitle: {
        fontSize: 13,
        color: COLORS.gray,
        marginTop: 2,
    },
    faqContainer: {
        backgroundColor: COLORS.white,
        borderRadius: 20,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    faqItem: {
        borderBottomWidth: 1,
        borderBottomColor: COLORS.lightGray,
    },
    faqHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 18,
    },
    faqQuestion: {
        flex: 1,
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.text,
        paddingRight: 10,
    },
    faqAnswerContainer: {
        paddingHorizontal: 18,
        paddingBottom: 18,
    },
    faqAnswer: {
        fontSize: 14,
        color: COLORS.gray,
        lineHeight: 20,
    },
    footerSection: {
        marginTop: 40,
        paddingHorizontal: 20,
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 20,
    },
    legalLink: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    legalText: {
        fontSize: 13,
        color: COLORS.gray,
        fontWeight: '500',
    },
});
